version: '3.8'

services:
#  mysqldb:
#    container_name: mysqldb
#    image: mysql
#    ports:
#      - 3308:3306
#    environment:
#      MYSQL_DATABASE: hibernatecoretest
#      MYSQL_ROOT_PASSWORD: 1234567890

  springbootapp:
    image: springbootapp
    build: .
    ports:
      - 8000:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlname:3306/hibernatecoretest
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234567890
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    networks:
      - huynv

  prometheus:
    image: prom/prometheus:v2.35.0
    networks:
      - huynv
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana-oss:8.5.2
    pull_policy: always
    networks:
      - huynv
    container_name: grafana
    restart: unless-stopped
    user: root
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
      - GF_LOG_MOG=console file
      - GF_LOG_FILTERS=alerting.notifier.slack:debug alertmanager:debug ngalert:debug



networks:
  huynv:
    external: true